### ISSUE TITLE
Having issues with my own data.

### ISSUE THREAD

**Issue by Rotoslider** [TixiaoShan/LIO-SAM#202]
This is not a error in the code its a lack of understanding by me. I did not know where else to post this so please forgive if I did in the wrong place.  I am new to ROS and Linux. So please bear with me. 
Setup is: Jetson AGX, Ubuntu 18, ROS Melodic.
Velodyne VLP-16 with Garmin antenna and a XSENS MTI-7 Development Kit 9 axis IMU with GPS and antenna.
 I installed LIO_SAM and can read and play back your sample bag files. I can see data from my Velodyne VLP-16 in rviz using" `roslaunch velodyne_pointcloud VLP16_points.launch calibration:=/home/lbackpack/Downloads/VLP-16.yaml`" and Then I launch LIO_SAM: `roslaunch lio_sam run.launch`
If I select Fixed frame in rviz as velodyne and under point cloud select /velodyne_points as the topic I can see the point cloud live.
I obviously am doing something wrong but searching for more than a week I cannot figure out the proper way to set this up. My IMU data is showing up in the sample code that comes with the MTi IMU. Its topic is imu_link. 
I think I need to edit the params.yaml file Topics section to the topic names velodyne_points and imu_link but it did not change anything. 
Could you offer some suggestions or links to where I can learn more about setting this up to work with LIO_SAM.

thanks for your time and software

**Comment by Rotoslider** [comment]
I went through all the rostopics the IMU publishes and I actually needed imu/data instead of imu/link. I now have to sort out the Extrinsics. 
My IMU outputs:
```
rosmsg show sensor_msgs/Imu

std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
geometry_msgs/Quaternion orientation
  float64 x
  float64 y
  float64 z
  float64 w
float64[9] orientation_covariance
geometry_msgs/Vector3 angular_velocity
  float64 x
  float64 y
  float64 z
float64[9] angular_velocity_covariance
geometry_msgs/Vector3 linear_acceleration
  float64 x
  float64 y
  float64 z
float64[9] linear_acceleration_covariance
```
Will the above format work with LIO_SAM?
Currently I can see the point cloud and the blue line for the IMU but it jumps wildly and then stops in under a minute. I assume its either the format or the position of the IMU.
The IMU is X forward Y left and Z up
The Velodyne is setup like your image in the Readme. I have some confusion in that the Velodyne manual shows Y forward not X if its setup like how you picture it. 
Any suggestions?
thank you in advance

**Comment by Rotoslider** [comment]
Seems like most issues here of late by everyone fall on deaf ears. But I will try anyway.
I used lidar_imu_calib to get the extrinsic numbers and enter them into the params.yaml
```
extrinsicRot: [0.928163, 0.357224, 0.104424,
                  0.263263, -0.828503, 0.494242,
                  0.262319, -0.431246, -0.86303]
  extrinsicRPY: [0.928163, 0.357224, 0.104424,
                  0.263263, -0.828503, 0.494242,
                  0.262319, -0.431246, -0.86303]
```
I uncomment the debug lines in "imuHandler()" of "imageProjection.cpp" so I could see the IMU data from LIO_SAM
```
 IMU acc: 
x: 1.0349, y: 4.56354, z: -8.62061
IMU gyro: 
x: -0.00505129, y: 0.00119266, z: -0.00181667
IMU roll pitch yaw: 
roll: -2.64178, pitch: -0.263641, yaw: 2.48605
```
This data is very different from my rostopic imu/data
```
header: 
  seq: 173683
  stamp: 
    secs: 1613187558
    nsecs: 764913859
  frame_id: "imu_link"
orientation: 
  x: 0.00228874385357
  y: 0.0174813140184
  z: 0.895720899105
  w: 0.44426715374
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.00156741612591
  y: -0.00206008600071
  z: 0.0018866736209
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: -0.112504370511
  y: 0.323832839727
  z: 9.80090236664
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
Any ideas on why its so different and what I can do to fix it?
Velodyne VLP16 and Xsens MTi7 IMU

thanks in advance
