### ISSUE TITLE
Issue with IMU config. ( Livox Horizon w/ External IMU )

### ISSUE THREAD

**Issue by Ab-Tx** [TixiaoShan/LIO-SAM#405]
Hi

I am having some trouble getting LIO-SAM working  with my own hardware. 
I am observing behaviour like described in issue #94.

For these tests, the LiDAR and IMU are not moving.

![terminal and rviz](https://user-images.githubusercontent.com/60508542/223776412-f489f52a-062a-452a-97c8-968ec5269adc.png)

I'm using **ptpd2** for synchronization. These are two headers recorded at the same time. There is a difference on the "nsecs" parameter, which is around 95 ms.

IMU message header:

    header:
      seq: 4133
      stamp:
        secs: 1678293435
        nsecs: 194799837
      frame_id: "imu_link"

LiDAR point cloud message header:

    header:
      seq: 91
      stamp:
        secs: 1678293435
        nsecs:  99923849
      frame_id: "livox_frame"
    height: 1
    width: 24000

It runs without any problem when working with the provided Livox dataset (I am using TixiaoShan  **livox_ros_driver** package, also had "useImuHeadingInitialization: false" when playing the dataset). 

### - **Hardware:**
Livox Horizon
Xsens MTi-680G

The IMU alignment is the same as the LiDAR so I have set both  "extrinsicRot" and "extrinsicRPY" to identity matrices.

### - **params.yaml**
What I have changed on the LIO-SAM  **params.yaml**:
```yaml
  # Topics
  pointCloudTopic: "points_raw"  
  imuTopic: "imu/data" 
  odomTopic: "odometry/imu"
  gpsTopic: "odometry/gpsz"

  # Frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"
  
    # GPS Settings
  useImuHeadingInitialization: false 
  
    # Sensor Settings
  sensor: livox 
  N_SCAN: 6 
  Horizon_SCAN: 4000
  downsampleRate: 1 
  lidarMinRange: 1.0 
  lidarMaxRange: 1000.0 

  # Extrinsics: T_lb (lidar -> imu)
  extrinsicTrans: [-115.0, 0.0, 63,26.0] # x y z 
  extrinsicRot: [1, 0, 0,
              				  0, 1, 0,
               				  0, 0, 1]
  extrinsicRPY: [1, 0, 0,
               				  0, 1, 0,
               				  0, 0, 1]
```

With the provided bag file I use the default values for _extrinsicTrans_, _extrinsicRot_, _extrinsicRPY_ and use /imu_raw instead of /imu/data. 

On the recorded bag I'm pointing the LiDAR at a corner (from the ground pointing at the roof), that's why it looks like it is tilted.

### - **tf tree**

![tf_tree](https://user-images.githubusercontent.com/60508542/223779369-65ca52c3-4b95-4cf2-9c05-5b7f30e93c50.png)

### - **bag file**
Here is a bag file recorded with my setup.
https://drive.google.com/file/d/1vHyeEK8l7XN48wCtQlUm2okEzSpmU_vc/view?usp=sharing

Any suggestions on what I should tweak?
