### ISSUE TITLE
Large drift and rotation upon initializing the mapping processs in ROS2

### ISSUE THREAD

**Issue by wxyLuna2024** [TixiaoShan/LIO-SAM#505]
Hello,
Thank you for creating this repo. I am working on mapping KITTI360 with LIO-SAM in ROS2 humble.
For the extrinsic, I am using the KITTI extrinsic posted on readme.

![Screenshot from 2024-07-23 18-33-38](https://github.com/user-attachments/assets/ba4477e2-5591-42ca-96ca-90d1d534c2e3)
The green trajectory is the GPS trajectory(gt). The pointcloud reconstruction failed at the beginning when pc are projected then it started to spin and fly around, similar to #433 . I also noticed that the pc loading speed is much slower than GPS. I have already set the loading speed to -r 0.1.
I get error messages like "Lookup would require extrapolation into the past." "Large velocity (38.120705), reset IMU-preintegration!"
![Screenshot from 2024-07-23 18-30-06](https://github.com/user-attachments/assets/ff048541-8afd-44eb-9cc5-1ff7083d85a9)
![Screenshot from 2024-07-23 18-30-24](https://github.com/user-attachments/assets/ac1ace8a-b54a-4b8a-9dd9-52db5adfed90)

Interestingly, same thing also happened with another dataset I have, which was tested on another PC with same ROS2 yaml setup and produced perfect mapping results. 
![image](https://github.com/user-attachments/assets/683c0a8c-b12e-4da1-9ab2-2e5f5c5e0545)

So I wonder if my problem is related to #437 . Help will be much appreciated.

**Comment by ZaynabEM** [comment]
Hello,

I am having similar issue applying the code for a dataset that I recorded on a ROS2 instrumented car having VLP16 and hesai pandar, and used the Hexagon Novatel pwkpak7 for the imu, odom and gps topics.

The `params.yaml` is the following : 
```yaml
/**:
  ros__parameters:

    # Topics
    pointCloudTopic: "/velodyne/velodyne_points"                   # Point cloud data
    imuTopic: "/novatel/oem7/imu/data"                        # IMU data
    odomTopic: "/novatel/oem7/odom"                    # IMU pre-preintegration odometry, same frequency as IMU
    gpsTopic: "/novatel/oem7/fix"                    # GPS odometry topic from navsat, see module_navsat.launch file

    # Frames
    lidarFrame: "velodyne_frame"
    baselinkFrame: "base_link"
    odometryFrame: "novatel_frame"
    mapFrame: "map"

    # GPS Settings
    useImuHeadingInitialization: false           # if using GPS data, set to "true"
    useGpsElevation: false                       # if GPS elevation is bad, set to "false"
    gpsCovThreshold: 2.0                         # m^2, threshold for using GPS data
    poseCovThreshold: 25.0                       # m^2, threshold for using GPS data

    # Export settings
    savePCD: false                               # https://github.com/TixiaoShan/LIO-SAM/issues/3
    savePCDDirectory: "/Downloads/LOAM/"         # in your home folder, starts and ends with "/". Warning: the code deletes "LOAM" folder then recreates it. See "mapOptimization" for implementation

    # Sensor Settings
    sensor: velodyne                               # lidar sensor type, either 'velodyne', 'ouster' or 'livox'
    N_SCAN: 16 #64                                   # number of lidar channels (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
    Horizon_SCAN: 1800                            # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
    downsampleRate: 1                            # default: 1. Downsample your data if too many
    # points. i.e., 16 = 64 / 4, 16 = 16 / 1
    lidarMinRange: 1.0                           # default: 1.0, minimum lidar range to be used
    lidarMaxRange: 1000.0                        # default: 1000.0, maximum lidar range to be used
...
```

But I am getting a very weird spiral accumulation of the data more than the creation of the map.
![image](https://github.com/user-attachments/assets/3f26a105-ece5-47c3-8c37-9e6d2767e2d0)
@wxyLuna2024 were you able to resolve the issue?
@TixiaoShan can this be related to a calibration issue, or is it another problem?

Thank you in advance for your input.
